[plugins]

jmh = { id = "me.champeau.jmh", version = "0.7.2" }

[libraries]

assertj = "org.assertj:assertj-core:3.26.3"
commons-csv = "org.apache.commons:commons-csv:1.11.0"
commons-math = "org.apache.commons:commons-math3:3.6.1"
commons-math4 = "org.apache.commons:commons-math4-legacy:4.0-beta1"
commons-numbers-combinatorics = "org.apache.commons:commons-numbers-combinatorics:1.2"
commons-numbers-gamma = "org.apache.commons:commons-numbers-gamma:1.2"
commons-rng-sampling = "org.apache.commons:commons-rng-sampling:1.6"
commons-rng-simple = "org.apache.commons:commons-rng-simple:1.6"
commons-statistics-distribution = "org.apache.commons:commons-statistics-distribution:1.1"
equalsverifier = "nl.jqno.equalsverifier:equalsverifier:3.16.2"
guava = "com.google.guava:guava:33.3.0-jre"
jackson-annotations = "com.fasterxml.jackson.core:jackson-annotations:2.18.3"
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.18.3"
javacsv = "net.sourceforge.javacsv:javacsv:2.0"
jexl = "org.apache.commons:commons-jexl3:3.4.0"
jpx = "io.jenetics:jpx:3.0.1"
mvel = "org.mvel:mvel2:2.5.2.Final"
nashorn = "org.openjdk.nashorn:nashorn-core:15.4"
opencsv = "com.opencsv:opencsv:5.9"
prngine = "io.jenetics:prngine:2.0.0"
reactor-core = "io.projectreactor:reactor-core:3.7.4"
rxjava = "io.reactivex.rxjava2:rxjava:2.2.21"
supercsv = "net.sf.supercsv:super-csv:2.4.0"
swagger-models = "io.swagger.core.v3:swagger-models:2.2.29"
swagger-parser = "io.swagger.parser.v3:swagger-parser:2.1.25"
testng = "org.testng:testng:7.10.2"
