[versions]
assertj = "3.27.6"
codemodel = "4.0.6"
commons-csv = "1.14.1"
commons-math4-legacy = "4.0-beta1"
commons-numbers-combinatorics = "1.2"
commons-numbers-core = "1.2"
commons-numbers-gamma = "1.2"
commons-numbers-rootfinder = "1.2"
commons-rng-sampling = "1.6"
commons-rng-simple = "1.6"
commons-statistics-descriptive = "1.2"
commons-statistics-distribution = "1.2"
equalsverifier = "4.2.5"
guava = "33.5.0-jre"
jackson = "2.20"
jackson-databind-nullable = "0.2.8"
jackson-datatype-jsr310 = "2.20.1"
jacoco-agent = "0.8.14"
jakarta-annotation-api = "3.0.0"
jakarta-validation-api = "3.1.1"
javacsv = "2.0"
jexl = "3.6.0"
jmh = "0.7.3"
jpx = "3.2.1"
mvel = "2.5.2.Final"
nashorn = "15.7"
openapi-generator = "7.17.0"
opencsv = "5.12.0"
prngine = "2.0.0"
reactor-core = "3.8.1"
rxjava = "2.2.21"
supercsv = "2.4.0"
swagger-models = "2.2.41"
swagger-parser = "2.1.36"
testng = "7.11.0"
version-catalog-update = "1.0.1"

[plugins]
jmh = { id = "me.champeau.jmh", version.ref = "jmh" }
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
version-catalog-update = { id = "nl.littlerobots.version-catalog-update", version.ref = "version-catalog-update" }

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
codemodel = { module = "org.glassfish.jaxb:codemodel", version.ref = "codemodel" }
commons-csv = { module = "org.apache.commons:commons-csv", version.ref = "commons-csv" }
commons-math4-legacy = { module = "org.apache.commons:commons-math4-legacy", version.ref = "commons-math4-legacy" }
commons-numbers-combinatorics = { module = "org.apache.commons:commons-numbers-combinatorics", version.ref = "commons-numbers-combinatorics" }
commons-numbers-core = { module = "org.apache.commons:commons-numbers-core", version.ref = "commons-numbers-core" }
commons-numbers-gamma = { module = "org.apache.commons:commons-numbers-gamma", version.ref = "commons-numbers-gamma" }
commons-numbers-rootfinder = { module = "org.apache.commons:commons-numbers-rootfinder", version.ref = "commons-numbers-rootfinder" }
commons-rng-sampling = { module = "org.apache.commons:commons-rng-sampling", version.ref = "commons-rng-sampling" }
commons-rng-simple = { module = "org.apache.commons:commons-rng-simple", version.ref = "commons-rng-simple" }
commons-statistics-descriptive = { module = "org.apache.commons:commons-statistics-descriptive", version.ref = "commons-statistics-descriptive" }
commons-statistics-distribution = { module = "org.apache.commons:commons-statistics-distribution", version.ref = "commons-statistics-distribution" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version.ref = "equalsverifier" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-databind = "com.fasterxml.jackson.core:jackson-databind:2.20.1"
jackson-databind-nullable = { module = "org.openapitools:jackson-databind-nullable", version.ref = "jackson-databind-nullable" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson-datatype-jsr310" }
jacoco-agent = { module = "org.jacoco:org.jacoco.agent", version.ref = "jacoco-agent" }
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation-api" }
jakarta-validation-api = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakarta-validation-api" }
javacsv = { module = "net.sourceforge.javacsv:javacsv", version.ref = "javacsv" }
jexl = { module = "org.apache.commons:commons-jexl3", version.ref = "jexl" }
jpx = { module = "io.jenetics:jpx", version.ref = "jpx" }
mvel = { module = "org.mvel:mvel2", version.ref = "mvel" }
nashorn-core = { module = "org.openjdk.nashorn:nashorn-core", version.ref = "nashorn" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
prngine = { module = "io.jenetics:prngine", version.ref = "prngine" }
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor-core" }
rxjava = { module = "io.reactivex.rxjava2:rxjava", version.ref = "rxjava" }
supercsv = { module = "net.sf.supercsv:super-csv", version.ref = "supercsv" }
swagger-models = { module = "io.swagger.core.v3:swagger-models", version.ref = "swagger-models" }
swagger-parser = { module = "io.swagger.parser.v3:swagger-parser", version.ref = "swagger-parser" }
testng = { module = "org.testng:testng", version.ref = "testng" }
